### PR TITLE
build when tags are pushed

### PR DESCRIPTION
**Pull request by mrwanny**
I would like to allow the plugin to support tags
i.e. when an annotated tag is push it should trigger a build.

### CODE REVIEW

**Comment by bassrock** [comment]
@mrwanny Please add a checkbox so users can disable this if they do not want it.

**Comment by mrwanny** [comment]
I thought about that but I am not sure we need an additional checkbox.
Branches to build -> Branch Specifier (blank for 'any') is already controlling with ref need to be build.

**Comment by bassrock** [comment]
Yea, but for instance my setup I have it building all branches, but I do not need it building a tag.

**Comment by mrwanny** [comment]
I forgot, you also need to add +refs/tags/*:refs/remotes/origin/tags/* into the Advance tab :-)

**Comment by bassrock** [comment]
?

**Comment by mrwanny** [comment]
As far as I know, by default the git plugin does not fetch the tags ref, it only fetches the remote branches ref, see below 
http://erics-notes.blogspot.com/2013/05/jenkins-build-latest-git-tag.html

**Comment by koglinjg** [comment]
+1, I believe what @mrwanny is saying about it not fetching, or building, on tag pushes without the refspec change is correct.

**Comment by bassrock** [comment]
ok. Will be happy to merge, can we add some documentation about it first since its a bit confusing unlike some of the others features, in my opinion.

**Comment by mrwanny** [comment]
I did add a small section into the REAME.md, please let me know if it is sufficient. Thanks

**Pull request merged**
