### PR TITLE
Update GitLabWebHook.java

### PR DESCRIPTION
**Pull request by eltados**
Fix the null pointer exception

### CODE REVIEW

**Comment by eltados** [comment]
Resolves issue #37  ( I think )

**Comment by kasper-f** [comment]
This Pull Request will not be needed in case Pull Request #36 is accepted as we then will use the data from the git plugin to determine what branch  sha1 numbers the build covers instead of the build parameters.

**Comment by kasper-f** [comment]
@pmalek Yes, since I have made this changes I have not experienced any problems and as so the #37 is solved for me. 

Please note:  The entire content of the getBuildBySHA1 function is changed in my commit and that the pull request is __not__ yet accepted.

**Comment by bassrock** [comment]
@eltados and @kasper-f so do we want to use this not or #36?

**Comment by kasper-f** [comment]
@bassrock I think the changes in #36 is preferable as it uses the data from the git-plugin to determine the correct build instead of relying on the custom parameters (gitlabSourceBranch and gitlabTargetBranch).

On the long field I hopefully see the need for custom parameters as unnecessary when we find a way to start a merge build from code (without the parameters). I have tried figuring out the different actions used by the git-plugin to start the merge build but haven't succeeded yet.

**Comment by bassrock** [comment]
@kasper-f interesting. Sorry for the questions been a while since I have actively maintained this. Does this mean that gitlabSourceBranch and targetBranch are no longer required, even for merge request builds?

**Comment by kasper-f** [comment]
As fare as I can tell the only usage of this parameters (apart from the getBuildBySHA1 method where I have removed it) is in the onPost triggers used to start a build of the job.

As I found it a bit annoying that I had to setup this [parameters](https://github.com/DABSquared/gitlab-plugin#parameterized-builds) and use them in my [jobs git configuration](https://github.com/DABSquared/gitlab-plugin#using-it-with-a-job) my goal is to find out if it is possible to call the git-plugin actions directly instead of a ParametersAction and this way avoid the troubling configuration for on each new project I would like to build. Then we could reduce the configuration to be a checkbox in the trigger to select if we would like to build merge requests or not instead of setting up additional repository and branch specifier from the parameters.

**Comment by bassrock** [comment]
Nice I like that thought and that is the way I wanted the original plugin to work but could not figure out how. I'll leave them in the readme for now then until they get eliminated fully.

**Comment by bassrock** [comment]
This should not be needed do to #36

**Comment by eltados** [comment]
Sorry for the delay , I agree this change request is no longer needed

**Pull request closed without merging**
