### PR TITLE
JENKINS-28271 - Gitlab Plugin does not build Merge Request when first raised

### PR DESCRIPTION
**Pull request by jr4**
prevent NPE that was preventing the build from proceeding
tested that the build proceeds fine after that

### CODE REVIEW

**Comment by skyline-gleb** [comment]
@bassrock +1

**Comment by WonderCsabo** [comment]
I can also verify this fix works well.

**Comment by kleijnweb** [comment]
Running into this sloppyness with older version of GitLab as well. 

LGTM +1.

**Comment by WonderCsabo** [comment]
We are using an old version (GitLab 6.9) unfortunately. BTW, is this change working with the latest GitLab versions as well?

**Comment by kleijnweb** [comment]
It should. Looks compatible with examples from latest GitLab docs.

**Pull request merged**
