### PR TITLE
Gitlab action type env var

### PR DESCRIPTION
**Pull request by sullb**
Adding new environment variable to indicate if trigger was due to PUSH or MERGE.

This will allow for the use of conditional build step to change the behaviour of the build.

If this is possible another way, please let me know.

### CODE REVIEW

**Comment by bassrock** [comment]
@sullb Does this require a change to the setup process? If so please add it to the realm and add tot he pull request.

**Comment by sullb** [comment]
@bassrock setup should be the same, just an extra jenkins variable (${gitlabActionType}) is available for other plugins to use, I have added the extra parameter under Parameterized builds in README.md.

If you mean something else could you explain further please.

**Comment by bassrock** [comment]
Ok, and is the parameter required to add to the job or is it optional to add it?

**Comment by sullb** [comment]
@bassrock good point, I have clarified that it is optional in README.md

**Pull request merged**
